packages:
  - "apps/*"
  - "packages/*"

catalogs:
  tooling:
    "@biomejs/biome": "^1.9.4"
    "@types/node": "^22.13.14"
    turbo: "^2.4.4"
    typescript: "^5.8.2"
    vitest: "^3.0.8"
  react:
    "@types/react": "^19.0.12"
    "@types/react-dom": "^19.0.4"
